### ISSUE TITLE
[suggestion] vertical scrolling

### ISSUE THREAD

**Issue by AlbertRayquaza** [Hecsall/MAPI#1]
Self explanitory, something resembling the long strip feature on mangasee would be nice to have as a feature, and I imagine it's not too difficult to implement.

**Comment by Hecsall** [comment]
Hi @AlbertRayquaza, sorry for the late response, as of today I'm not actively working on this app since I found a better alternative ([Paperback](https://paperback.moe/)) that covers the needs I had when I initially wrote it.

If I'll ever resume the development of this app, I'll gladly implement this feature.
